### ISSUE TITLE
Time and Variation class simplification

### ISSUE THREAD

**Issue by diegomichell** [raydelto/srtsynch#4]
Hello, interesting project.

As I see the Variation and Time classes are almost the same wouldn't it be simpler just using one of them, for example instead of the Time#change() method  accepting a Variation object it could accept another Time object and the result would be the same, and so on in other parts of the code.

Note: I see that Variation it's maybe a more meaningful name in some places, but it's just a matter of commeting and putting the right names where needed.

**Comment by raydelto** [comment]
Awesome suggestion Ivan.  I agree that  we could achieve the same goal by simply using a TIme instance for specifying the variation that we want to perform on the file; nevertheless, I consider that by doing this, despite dropping some lines of code, would make our code a little bit confusing since we would be adding more than one responsibility to our Time class, which will break the Single Responsibility Principle (SRP).

Thanks for sharing your thoughts.

**Comment by diegomichell** [comment]
Ok, now I see, true it's a better practice to have both things separated since they have different responsibilities, and some methods would stay unused when it comes to treat Time as a Variation. I'll read about SRP, thanks.
